/*
 * Copyright 2023 Kevin Wimmer
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package io.github.kevinwimmer.gradle.tasks;

import static org.gradle.api.tasks.SourceSet.MAIN_SOURCE_SET_NAME;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;

import org.gradle.api.DefaultTask;
import org.gradle.api.Project;
import org.gradle.api.plugins.JavaPluginExtension;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

@DisableCachingByDefault(because = "Not worth caching")
public class GeneratePomProperties extends DefaultTask {

    @TaskAction
    public void generatePomProperties() throws IOException {
        Project project = getProject();
        try (FileWriter writer = new FileWriter(createDestination(project))) {
            createPomProperties(project).store(writer, "Generated by gradle-kie-plugin");
        }
    }

    private File createDestination(Project project) {
        File dest = new File(
                project
                        .getExtensions()
                        .getByType(JavaPluginExtension.class)
                        .getSourceSets()
                        .getByName(MAIN_SOURCE_SET_NAME)
                        .getOutput()
                        .getResourcesDir(),
                String.format("META-INF/maven/%s/%s/pom.properties", project.getGroup(), project.getName()));
        dest.getParentFile().mkdirs();
        return dest;
    }

    private Properties createPomProperties(Project project) {
        Properties props = new Properties();
        props.setProperty("artifactId", project.getName());
        props.setProperty("groupId", project.getGroup().toString());
        props.setProperty("version", project.getVersion().toString());
        return props;
    }
}
